# Generated by Django 5.1.7 on 2025-03-22 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('servings', models.PositiveIntegerField(default=1)),
                ('food_type', models.CharField(choices=[('plant', 'Plant-based'), ('meat', 'Meat-based')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('energy_usage', models.FloatField(help_text='Energy usage in kWh')),
                ('grid_emission_factor', models.FloatField(default=0.4, help_text='kg CO2 per kWh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TotalCarbonFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='Start date of the period')),
                ('period_end', models.DateField(help_text='End date of the period')),
                ('total_emissions', models.FloatField(help_text='Total CO2 emissions for the period (kg)')),
                ('transportation_emissions', models.FloatField(default=0, help_text='Total transportation emissions (kg CO2)')),
                ('energy_emissions', models.FloatField(default=0, help_text='Total household energy emissions (kg CO2)')),
                ('food_emissions', models.FloatField(default=0, help_text='Total food consumption emissions (kg CO2)')),
                ('computed_on', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was computed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('distance', models.FloatField(help_text='Distance traveled in miles')),
                ('mode', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
