# Generated by Django 5.1.7 on 2025-04-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodconsumption',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='householdenergy',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transportationemission',
            name='date',
            field=models.DateField(),
        ),
    ]
